# Generated by Django 4.2.5 on 2023-10-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0003_remove_ratingtable_project22_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtable',
            name='project1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='Generating strong password using python', max_length=2),
        ),
    ]
