# Generated by Django 4.2.5 on 2024-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0005_alter_ratingtable_project1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingtable',
            name='project1',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project10',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project11',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project12',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project13',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project14',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project15',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project16',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project17',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project18',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project19',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project2',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project20',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project21',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project3',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project4',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project5',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project6',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project7',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project8',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project9',
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_1',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Synergic Calculator', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_10',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Health Dot', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_11',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Online Attendance using Face Recognition', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_12',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Heart Disease Prediction', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_13',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Exquisite Checks', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_14',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Facemask Detection System', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_15',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='OTP Verification', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_16',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Language Translator', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_17',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Matrix Calculator', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_18',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Project Info', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_19',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Housing Society Management System', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_2',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='ID Card Generator', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_20',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Hangman', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_21',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Virtual Counselor', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_3',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Inventory Management', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_4',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Food Chatbot', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_5',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Incident Reporter', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_6',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Online Banking System', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_7',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Online Voting System', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_8',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Bus Times', max_length=2),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='No_9',
            field=models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Secret Code', max_length=2),
        ),
    ]
