# Generated by Django 4.2.5 on 2024-05-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0006_remove_ratingtable_project1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingTable',
            new_name='RatingTableOne',
        ),
    ]
