# Generated by Django 4.2.5 on 2024-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0007_rename_ratingtable_ratingtableone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTableTwo',
            fields=[
                ('Name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('No_1', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Synergic Calculator', max_length=2)),
                ('No_2', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='ID Card Generator', max_length=2)),
                ('No_3', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Inventory Management', max_length=2)),
                ('No_4', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Food Chatbot', max_length=2)),
                ('No_5', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Incident Reporter', max_length=2)),
                ('No_6', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Online Banking System', max_length=2)),
                ('No_7', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Online Voting System', max_length=2)),
                ('No_8', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Bus Times', max_length=2)),
                ('No_9', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Secret Code', max_length=2)),
                ('No_10', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Health Dot', max_length=2)),
                ('No_11', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Online Attendance using Face Recognition', max_length=2)),
                ('No_12', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Heart Disease Prediction', max_length=2)),
                ('No_13', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Exquisite Checks', max_length=2)),
                ('No_14', models.CharField(choices=[('0', 'None'), ('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='0', help_text='Facemask Detection System', max_length=2)),
            ],
        ),
    ]
